apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: churlesflows
spec:
  interval: 30m
  chart:
    spec:
      chart: n8n
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: n8n-8gears
        namespace: churlesflows
      interval: 12h
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: n8n-env-secret
      valuesKey: values.yaml
