apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: n8n-8gears
  namespace: churlesflows
spec:
  interval: 24h
  type: oci
  url: oci://8gears.container-registry.com/library