apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: churlesflows
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami-postgresql
        namespace: churlesflows
      version: 16.7.x
      interval: 12h
  install:
    remediation:
      retries: 3

  valuesFrom:
    - kind: Secret
      name: postgres-churlesflow-secret
      valuesKey: values.yaml

  values:
    postgresql:
      database: n8n-churlesflow
      persistence:
        enabled: true
        size: 20Gi 
