apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-postgresql
  namespace: churlesflows
spec:
  type: oci
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts