apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: churlesflows
resources:
  - ../../base/churlesflows
  #- cloudflare.yaml
  #- cloudflare-secret.yaml
  #- linkding-container-env-secret.yaml
  #- ingress.yaml
  