apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: churlesflows
resources:
  - ../../base/churlesflows
  - cloudflare.yaml
  - n8n-cloudflare-secret.yaml
  #- linkding-container-env-secret.yaml
  #- ingress.yaml # Using secure cookies is not possible to access with cloudflare/internal ip
  