apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:GCsui6I/gk8dnzRY/7pArrQcRQxqMkkdpvpik289PEUHL7sNvgBZvbwdjN5pTf60/IPKyJSk/gbs2BU9R/w0kGywUwCbKFAppnKuinvwV5cF4BcrT+2Nj4/wUKyq7lQtQZdM0uPOMPSZeiSnfM8jkZEwHRw4x0CJYRiiUbELR32DEm/QVb9K3dj00NhM8f6iKbPFec6I7cvX3tzCZfn6r7ax9J2m/AOvdOj9DG4WSX6o422uzirN2En7M2/XhlL6/nv9BYoYrWy4btRN6QTBkdjG7B84eV3sSDTkaBGCwYL2vk9xfahZ2anpK5o=,iv:7AROGDP5yrKk0agPoUTcOO2WDyPgoWisY8KZ79LjzuI=,tag:PsD0CcLYMJSHOs+3WLAdrw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeWcvWFRBZ1kzLzU0VHow
            bC9GL04xLzArcllUZnB3aDMwb0lvdkk1RFNNCnA4ZDRRVm9SS09mcy9RWDBoVXNY
            WjFlTXJSeTJaeXFJTGwreHp4TXg3Y1kKLS0tIFMyNExkZ2w2UW1tbEt6K1pzWHIw
            enNnQmpkdlhhc0VIRTF6cmhPWWtjbGMKF9mcEIgTdpEOa+eIPlBBUoj/oimQr+qr
            OC4vULZsG3p4895u3A05tI7VZ9rG+EEfVA2hF0PVO6F1s7HIde1nyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-25T21:06:00Z"
    mac: ENC[AES256_GCM,data:FGZzbSJUS+xFEvHJnbSLbK5SERIoN2wx1nM8H3qc1AKcmAFJhVqLes/MZ5BacgJpK7d5bgUWi4EXfiWEXdzWwjd3GCmGw572/vP9lXlqMpiHLgNI/jMotgOg5KIO5C/EHxdBaP3OflFnWE02H9Ej5Zs55rBpVIrySaYPEXOwdRU=,iv:K3WrP+hVIZTy7BNYdwxu6Qyc7+U1FfidtAgRB3SDrzI=,tag:2f2AdFrfD+qIkC9+mMSy0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
