apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./postgres/repository.yaml
  - ./postgres/helmrelease.yaml
  - ./secrets/postgres-churlesflow-secret.yaml
