apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./postgres/repository.yaml
  - ./postgres/helmrelease.yaml
  - ./secrets/postgres-churlesflow-secret.yaml
  - ./redis/repository.yaml
  - ./redis/helmrelease.yaml
  - ./secrets/redis-churlesflow-secret.yaml
  - ./n8n/repository.yaml
  - ./n8n/helmrelease.yaml
  - ./secrets/n8n-env-secret.yaml