apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: churlesflows
spec:
  ports:
    - port: 5678  # Port to expose; should match containerPort
  selector:
    app.kubernetes.io/name: n8n  # Match the label in the Helm chart's deployment
  type: ClusterIP