apiVersion: v1
data:
    AccountTag: ENC[AES256_GCM,data:U9I39Yk/uqssCGjknO/PDSGE48uiU3k3HFxCHpwe/Io6fJ5vlqHXxNc32C8=,iv:aqaedx2OSztd9MWmXkU2thFcnM7hhy330tPEni6v1Mc=,tag:RKpchdmTGhZThmyCbnC1yQ==,type:str]
    TunnelID: ENC[AES256_GCM,data:UuqCtIZ8NoQXsg/JYO9IflgLwXCngvDhf9q8I88rHbVRW7tDhmA02ZQVSRyYWuge,iv:gHzQv7cVi3xfGWwAo13hIHz2kY97xJHVrYB1fAC7YdQ=,tag:no/bDGxe2DJdY+R6RxRK0g==,type:str]
    TunnelSecret: ENC[AES256_GCM,data:iVE7FjbkwMt3eoeGh7u3q7KpI/rfVq8qpovv4hvCY+BBhOizVJk7Tj827dyhgMq2RBrqNbFvyN7UCb84,iv:Cy96/v3TAbJiy2V4IeNEIx2xFHXTsulC+ST2Kz98Wqo=,tag:A3M70RRZ7dzSt7dT70UIBQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OUwyVFFaOW92c0dheWZK
            V1dOQjNQQnpvNDJraFhJTldUMjRSVkdWMW5jCnNXdHZ1bFQ2OHRVcUhsQ1F1cDU3
            V2puRFE2aWFGWUFuNFQ2TjZJQmplTlEKLS0tIHNRbU1xQkZjUDVuQmFXV3pKcTcy
            REt6SytncjZFN2ZObkx0Ym5XZWVlT2MKSC33MX+3LaHOYw1uckkTP62LpZ/ETaLh
            icqpkVrw5KoCtBJ6FpY19MYeQvaVdfiWtvo2rcYKn9lNeYB6gCaCTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T01:18:23Z"
    mac: ENC[AES256_GCM,data:2aqWs16Gb6xVtE+ljv1ncQ72rCHCy+KpwnVJeq97qq9Wg8EXtrH3hiqDD2bryrBAouQH5H5DnKvbhwP4jH+tXhbvtItTHnd02UbKDO8k8uQF482IsbWHgQs9JAtw8ETVH2EtMk382sS0LWyMeECWCS9/jO1toDDEW5XRRLxKj1k=,iv:jY4zkjwfmO21cSyu+3C1ZKBPYbNo2G5k3E8i4PUWxP8=,tag:grdW4wmCPWDqUs3w0ANz1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
