apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: churlesflows
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: 18.1.x
      sourceRef:
        kind: HelmRepository
        name: bitnami-redis
        namespace: churlesflows
      interval: 12h
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: redis-churlesflow-secret
      valuesKey: values.yaml
  values:
    architecture: standalone
    auth:
      enabled: true
    master:
      persistence:
        enabled: true
        size: 5Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
        interval: 30s
        labels:
          release: kube-prometheus-stack

