apiVersion: v1
kind: Secret
metadata:
    name: n8n-env-secret
    namespace: churlesflows
stringData:
    values.yaml: ENC[AES256_GCM,data:0dX5zOpg4b0aBUwmqmzKnfmZkL1TeBI/6Bg+2xSBKhsLJFw4x8R8iZMBYhBACTiwRqGRt2R5Y1PskeXZNshJ7w2eHQh1F+rtgnWWvcEqBmwhhqVaIxAjDPlK9U2HEAVi27jcfuMOwrz7s3mx0wOkOTztuEEB65YOSytnbAu7ZSEqDxqXbOiDrz4yQNaMWuL/3gIQnIqi8Gc3+yeoAfOr7T13FB6Oz78z2V+NUQZcyyZQhwjY32RppQhOh6j9v6jk0vTsuwPPJTxMlVcP/JSX1D9CdqXYl7ucOGn9kXorWuBVO/hAU2Y9hq1kwu9t5OGOz4SSwBdr4hgVymsyeGrOnR68iwn+0kfIhYz1SKpvp1C9Uj67q7CDCEYeIAfFBPFbfeIxrqfjGuXcgQZh5KDjYTumA1oyUCFvtm+/dfKIQH3iftPg5tBPT/6hLD226zVl9xbW0Ci6DOl+XTErWUI5V5JMYBx5EmIBuxXEugZ5/j5RfNbCMlPkfPf2hVBF/7kWwzhvpaOHtOrvmMDqI/mL/vEt9c9z/hckAMPM78awjSh5n+UfxQa4EItgh57tHNAicYAiDS3HPBN8PlbSDvGQroRtYLAeHdRTwITBYfwctQ+Do4Ss6U5pt/zcXWU8PWO22Th5lnhrYRomZNA73U7r7xwBPr9BhYaRJeMIBaEscbYtBT9I0NTR6KXn3NUb8hb8M5hoovbkwqJzQBz4hXfhnKXj+pdSdAQpIB51J23m2MPFi0x7HErXMEuAfgq5IuWl1XGB6o7Ws9Q9Z94Bi51Hj4fTJ0phHTmdxcD1IPVeJytvxVTPzTicK+hrUVISne3uKU49YIxe0pIm3kigI8iDNlZtvmhWk6kKSphfWCRDAhR0Rw9l22ObJyTBWPtjaG0flXEOez+aCxR8pGeW5jf/Kr14s+k6TNcLC8Zs2sRtzXdpxZylKVcTWUR35eMeKU2sgTPqUH6MVNLP+xMh3bz3a2aXojDJGpKiGkIWmpcxu3OTE3KAHq8kauFwaIdLgF9dpCtHFTqdkn8C5Mv/r15VJYPLxThd3x+Pk2Oe2BuMHOYmL8P9KPXSBMZytw84yys89ngAaPyO1LPOcKP/TbthUBdwI0tWTPqg+21VIuV5kQhD9e5izhJE9QhxJzRpKEwDUNw+fi9TgfZH6SU8qgbonj585WA7rlTs2ATOU4I3qC/TzODiqUq7+aNB9O2NoMYIffmPrXsHZp52cZ3jGV92FWt0wV+Ue9xgS2NNgQZ89Z8xwaTDjb8l4No/Q0nQg+/t7kN/HcvijP57/bfKvW6O6T3XFEi9/XKCpaK+w5bNn65e1Ea3ZK3VcDyUuIAEkLuBVveJkKQG13jSvAYN+buWjdFr5uU/KHXN0qqPsxIgNTu9h0cPvSrwomnT27rc/jPT1kaF0IKQJylJW6iXTvClEb3ntyuBCPeG+SUWgZeHATamD9N0je51YyFUKNmpacVOYA7W1zFCBHc=,iv:uibD3VdQlzL5PhZccEBQGBrgbUZMTv8JBAB7gyfQOis=,tag:T6tcZ2S9+WYsJcQKxefALw==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVHFtYmJTanRlRGFiQ1h4
            aVFoU1BCTC9IUitNbmVyVU1Qazl1VEUrVFhJCjlOcE1pOEVtMGxvankzSlp0cFVn
            dnBPcUMzQUo3cUMzYmN2YzZTelhUQVkKLS0tIFE2YnhvdmY0Vkc5R0VIR1hHV0Rw
            QkdUVStGazhROWRaaGVQUHNsWHhFeFUKKFsUbOQ8VIhhj8WktW/oM+RqxJ0kenFo
            oPo4zl1zaKpxy0Mgiko0HhahP8pM42jbAFBol4w78rJRLb/n0zjOFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-26T12:35:38Z"
    mac: ENC[AES256_GCM,data:pfkjiCyuMAvXyP8fxOEasHDJRSBDjHFOdsy6gOMrzAnMpyoUBBYdQOJ/shS3UureU6DUBHBLjfSP+/0z0zjpeYk3RcJqy4c75z6w2qJpCj+3C4gEGBmbre6AHgdyzLf73WzskU6ogluZ1nD4X2v21VemOL6QiA6baLyBEkp/fk8=,iv:jsz+PDdGxFM0j4gzPzIibnRE6OZJKg0VGo/ConL+W3I=,tag:cmYONM7W2ntIx9IIlJ572Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
