apiVersion: v1
kind: Secret
metadata:
    name: n8n-env-secret
    namespace: churlesflows
stringData:
    values.yaml: ENC[AES256_GCM,data:sX852C02XUaQ8zON5ST5JMIQDf0ghazafS5wnsU6BJLcKRNco350dEkh9i/nU+vxHvJvB4iu9C/qqCMhRRlXn+vU+6o5KWl05ouYWGuFwofVEb4KVz/8xM8+ARp+6+u1ECqQKQW+zaa7bL2ctMTWisWrLCxieii8/6D4ehe4PkU3RoOnG6r5r85T2mOQ2tkgVP1UeoCVYkI778tKw7bw+ibAFgkHUQNlFCV2WDNcdHSyVGXDCxjkPw9WuLMxopkqmAKgebpkQEPvvC1EOGbyO0rOvtW0hHWAr5VqVtqf/bUEsXYLjX5RElwyKb2/MYjrrbH+0WX+nJim0phDerbkr9rEzeTiNOZ4scaktGITVNPnfr2RRa7bWSxyOcgVU2OHS81uaPiEvvVIr58r7Xws4VyiP3tNasIwf5TqMgvdSNUXHLbDzAa0DCYD3hCCprAS5dj4Rt6p98ZfBvxcviLUm7F990s6dola/dSn3JC3hRKsPHM1aeL/Nedue7JZGVPH3NdEx9GSI/Hk1M5QGNKZ+LrAArxN6isPxHnV3tDUxahF0vfeUFag4pBFUPkDiSr2B1EScpwHSwOR7kzvIIhq79I5Kx6b4KzU4UsqKHv72XXiF3Of3ZHbTWK1sjog8TKnFuD1sMVJyVlTc7e5NI8hMBg83N7MpisrzKX+sEv0hFnRvPGkQ4bAgb4Mmd/c+DDxoQuTov6V2DwMHzo+phcjrEozf/8c0mDA1KBn7wBXuM4dhCtpaqmXVQy8s4MN823tYRDLe+F2HbG3q9rjSXvGSomlyalkPgcgK0+aegQQQl7ASBda8vFst+K6kGgH+JExgvNda7sDbwDdFcRQJpwTnE2We/sIpm1b9WcAAIPTldRZzbxRQ6gln51QFTNEjkU2g0WfvatCut4iQLX0SAaVrLtjde+l8UiHuNKxNPaQRnzEsZU0azJ2yxcg8sWLJnWwPYk1dsSxolgljS5vhM7UbFx2BcNaaeQ3lVyrmIV53IaAUpDgLFOzipMUV9BanjZfv5bLwyYugz9KaOxa8QX9jY8DocFh2RY0MoQHIH9Ee38gkLxZJ15siUa8bayHMHWS1ECT4w==,iv:uzVbFpN0HmAOblHMucEPkuZbK3OV4rtCDE0MN+TGPUU=,tag:fNRAvolP8Lyog1UoW9VAEA==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSWJzUWE3L0ZaRFFDRFVE
            YU10aGZDQk95YWNwNTBVUWhyYm5EVnVKSDBBCjZOakx0Q1JSWjZsV2VtL1F5Yytk
            Q0syNStyWW13WjBOTEFHRXJrWUQ0OVkKLS0tIEdsdlNKbnp1QU5DSTJEQVFpZDBN
            M0ZGWG5kZ01TQ3h6Y201QTJqZlB6SGMKB9IDi867X7GL1nycHfdfpoRMN659HTuW
            E9NzhaE6iLfmB5MwYfgzmVfMCEem5evr5X6eNB4tqmfCEogZWKA/Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-26T13:05:20Z"
    mac: ENC[AES256_GCM,data:19pH3uIlKKvhEp2Y8+DBXbCOBuSD7xyTSBkWoxAw2xerGaeuzI+v0ym+GrPKnEU0hhSv3Ux/tq4deQJpZ4+RV1dzLEoH9h1Nfy20f7X5wVlqCJVRUyJp03JaKQfz/kKfG8fVs/psWcdpIHhWH3fZmM10tuh5vn+Mi1D24bfGTPw=,iv:BnUwFqzZQoEc/Vm8TTdUImNtlJ7xw4O6MAP/YUPW+1w=,tag:XM11KEpTZvUpJLSlozIAKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
