apiVersion: v1
kind: Secret
metadata:
    name: n8n-env-secret
    namespace: churlesflows
stringData:
    values.yaml: ENC[AES256_GCM,data:iHy/G44rez9a3L63H8YKVJF6Y9LSOcyVrA7uiaWCcX0oKSKTEYDupOQbI5cmdIOvHkb28yAASvoJUEwE2/kdb/oECNPDpfxrSYtXPVhkGHYEzwPrKqwdwlw5lKJS0zxE7hRZ70S8m7H9exic8owLzvR//1Ssu+X2ipQJH2FRv0oDYp3fdNeIIWTz5ipyldBIv7CURp69VyM3R+2SK4RylyNhCPXK7hSEtIwej6c1xe+qU2yR55ohgxeO0CbQrxalcWOd+JqBlf6ACRfA/wEkZo8IoUN8wWb5dlMWDUfDt+9nGlZ6LfX0E4nLb+432aZ8T6BBsPGb6XLoGtLXkCa+NpR2U8vw/+dyM/2Ij748vuaf4OYJMjpNvLd2oXSaqSribZB8ja5+Im2rGIBs3o4IkHeAbbGzfGH5cNc2OKHYlQwI8HNSlMesztxsudugTr7ZDsxF3mLdMaL3HevyRha8jbZ3hv/F2i5wskRr0i4SlKVB4eALjzg7RXekDgukQMUXls5hfLfVJAr+OuNJmZzw+chZ0QOanTOKuRd7r7I3Hm0Y3Mc5drSgHYIakeLmal0xX6B+OLrdpx61r4/y3JLXsYpuidPeMC5d7VGDntvYA1ZD6tYLvktsn8c9L085aQWL31tCmRTOnLzOkLenrCLc6QiS764xLbVKNdCKhll3m/yVwQ0VI0qvt3AidIc692ehgXjLTvyHR0oDtaj1r3XilL83UQqvXftLXlEIad535bQf/64+rJWKLzf6CdOCIP046iJYTYDuYuzZQ3/iVCY51U1B3JvbvziGu1XLzbh2WizWR3/lV/VcnD89E5M6guR5j/p5gyEnwUGE5yt7O/Qk/tXNXWd2e2VDsK80cL6KtGMARvLYXmXKmk83/RMogQ+l50UJJdjD1F7XGTBOP1sBdNem0HatMXkU/8rvlbUn2ILA6MupA3hP+bWODJ0tGDHfqr3/jWkiVlDj4tO2a/A0sq6CztiufZWOeWdZGTqKZNLxKsNCInsYnBCiEYuoPHjM3yVKI2JYZZlXwdMn1QEJZLA8XREefMR2QsSXW22qM6M2PDiWWV9mPSqwokMV9nw5rpdehEBmUX7MFl8U2JHEJNFYaxM7Fb7nKcfbpTwNnUyvPyt/crMqqK6nvAmbPYAkfXOVWrSTR8dqA8vamc1G9UOaach21cON3DoxH4qQ48MAxmlpJ3di6Wv/8uLgnWhixjiYF7g/8V0fOzVYRYUkTipYHXdrmvZB6vHIF8bPmL9ql4E4MdAedblJk0pApvcY9NLMMBRkWmvzjYA8J6a06yO1OiY2PA67ntXSraVl/XmK8MmnZQwtD9AlYYNIKVC3yyjTDxRob6CATar0F4gyYcWBTMBbmw==,iv:UvLyByDXv14EXnnjuVuEOJFwxxVxSE+9zolzWQSqjvs=,tag:HIb2CNR0uxKJGhXULh5TdA==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z0NOdnErTTRIdFVUWmJE
            OER4NE5SQ2VtalRnYVIyUmJiSXVmb3BJOFZ3Ck1vNGdmQzJBSnBqZVcrUEJHMEF5
            WGFpNzRjcFlnbitXaUVLV1lqdmtCSmMKLS0tIFZSU1I3VjZwYWVFSEZlb0xFNjlu
            UEkzYWt5NEpsRk1FYmdHSlQ5QTNRVzAKUbLpU2nq+YfFDx5WA2LPD05JjsMhslZR
            HZEvKjCdgSB2DE7g8e2w4diLAo8iN9YLlns2aeUx3P77rQWCIiSEQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-26T12:50:02Z"
    mac: ENC[AES256_GCM,data:qaVvr78mAeZK4cGYxrWQf4jTO8Ytebvmu5otE87/Y8PJmCE7V0dXvI3r538gzMrk9WnOulJK1CdrLgg6A40QNODIyz8KZWXd1v4moRZqAqUZXGtJkq8t7iNzK/l+i+7qAiW8uXjXnKySvi5h40jByYkA9sWZo9m9wsMHiRu63LQ=,iv:8UE6TIW8gkuUDz9OgHgS/JtqNq/wlDBRUxgtpS731/4=,tag:s/dsAldUDCAa+D+WweY0QA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
