apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:nrfW6BBl6P05e3A9s6/Aa3GWPgBViW/unPrDhtUXeeOaa/JkDmxqWDhBy5DIVfzQLiHvk5pPN0H7uPOS6zj90xkGYoQLSWlR5Y0mURZBYoz6LEP28uHQ1rL0PAZYz6B5bnhPuI13we++5bM4T600Q9fj2DXgGOGASGEXPa5YcODosUMn++KvTDXQBsq2+N7j,iv:pGjXFZGvZ4SxcH9Lj2NjjL4p9kCRHDaeECNmar8B2Gg=,tag:blxdZ9L5+2iKStng/T/sxw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: postgres-churlesflow-secret
    namespace: churlesflows
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRGZLL3JZYVNZNkx0UCsy
            Z0ZJcEFUNGVsQXkvWkVGNFh0SXpJZWJsRmxnCnNmY1I1WlpKQ1gvUjMyeHNpVEp1
            VHpEY2hXS2FBS0dzZnJnc2VmYlZNMmcKLS0tIHJGbzBHUDVyd2I4a0gzZDNQSDlD
            U3NRQjZyZjhrOGRlY2w2M1J5L3VlaUEKPjr6wRtd+kiIGJEKL4+uyqz4nEXg+rVN
            gmUjQGykWRzNCxndBoLLbEvShrExjHKFWXr76/vgDXadR+uPO7XMYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-25T02:19:54Z"
    mac: ENC[AES256_GCM,data:LKg0h+H2iWdS6H4/5ydIlXvjw3tvz27+xG6YZWxRgWHxX8sjJ2k1VUUK9JX6f8DFBR8NkVtKqivN6LgIBUaGF84+/Eda4IOJo9ZPF5sFVYvepbH7M0r0L6g4Ds3AZttlLOxvqNmKMdMX8BubJVY+525RblU4WdLSLQjxCowVfM4=,iv:2V/bc4j2MtB4jHOxcp2p7ShZ4BGvXBwK1CrvRoxS5J8=,tag:oOCX+Ub5FTMXqSo8ZQ378A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
