apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:r/39bUYo6e4O/ujPTVRi5NoiAOZqNd2XF8A0VzbhibjhpjByPMLxbbeunAY3PzvAU1rQV48d+A3mdDjVZy+azFmkfUBW/nn8rpz46UzS80POI0VSEITvQ39iKjSxs+cAhjEjtEneMHMCJdGGP9c5DR3KoRwlaNHp0J6cGNdH9+XvkWBXcNuf93ZjFssI12tR,iv:GGZqqnalkIkMBcB12Je3w3o6qfSx7LVLiWCngYuhI9E=,tag:UxCnzGMgEOFtJr4Q8icvsA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: postgres-churlesflow-secret
    namespace: churlesflows
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxREdTVWg5NGFYdGRURlVu
            ZGEveW9abkl1b2lpTmhOQzdSK2xYd2t4L0UwCmFwcktTbzdtbDdTQi9ESERHamN2
            VjI5Mko0VDJjTVpzVVk4STVoNGlMNVUKLS0tIE00TENDVWppR0pSdmNtRUkvNmFJ
            RXRtVkk3enJIZDFWc2Y0RmtMNTlrV1EKivz7q4uPa7UBRlNAMK0lv1HaQ/ebH+xH
            3X7eOCDJgJR09EiwHX4kp1eUVt3vcufurbaavOeOPtPqox6WnFpfkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T14:50:40Z"
    mac: ENC[AES256_GCM,data:cZFhHwNF0h7lrXYXH5UVLRoJP1Z2MBA3tbYoied/k8fByKwis4bFfqk4OsifePMDjaXgkhDqJ06p4mBQoZ8SMreVS13KD6grUSM2dRELRaCDCjMyRkr4b+uj2ogDU35+rSn3WDjBcx3lxjO9SaVv+60gcmMpE+juj5q6mtRH3QU=,iv:5jb4ba5RTNbVz55JOEpXbloIBstoRHHUqEj0+ul4lTE=,tag:k1lIJVVKMPoj81c9KcXJ5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
