apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: rayces-production
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:LrLqGyg3o5CYOdc4asw4N9y7kY4uGGsIAEoB55yaYf8HJl54VBSU1UhCYhG8Q1xpY1WdjTxc7UKtj1/aSLnakL2BiiuZ9Q+HHdqbZJY0XYhTKNbQYVH5TjKTlEPYtM+5J/P/xYE7jMZhYhEqtymti0FPKsWkJFP7Rz5Ifrrh8aXIqblfVeE79JR2+0eIJ8B/43TETEJT+iagv0rewHsqJ6KU83bMEpTGKossIEzCaG1tzbmwMhmdeN54Kd3bdxfhV4J8dljDRIpKiaKTr+v+LWdmNg2Pb05qrh0Yawb1,iv:L7l+W8TAQvSWcFOx6pvKOWAi1x3fnQG54ZyPOtJWLI0=,tag:xwDfuULPiAxFUefb9rbNzw==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSi9rSlNwVis5aFF5UXBH
            aXVVYUlJWHpnaWxLekRvSnMvMG1oQjMzY3hvCkx5TURUV2tRb1M1NmJMdVJYN2dh
            aFpTek5vOXpieFR3SlIzaUJBRXYvUWMKLS0tIHFJTkNQNG5lY1ErV1VlQWh2Vis3
            VDVhT1pUeG1ISjUrUHQ5aGJGZE1UdncKHhXHUVNravNOkYgPQxemjbOMfm3T23lQ
            X5crv9avI+7o2VkbW4q5+uxFPYK7vAlo1COiYNIH2u+vSVbLBN+3Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:28:49Z"
    mac: ENC[AES256_GCM,data:JbqStKVRA6Flx7+yMQ1A6LGFfOjKBAru+o55IX3Z4Ec1/b3oOohXS2o60yPspbErZghkd6UUvoFLzZ+f5tzQdAHbzK3VmqWIfSt6f9vYzqglkLEU8ecnvkKMjbuF3+AjRugqCTX64FW2CVYoBcE1NmPQW/trYRAw0qObchYksB4=,iv:xaj5Lx/0p57NDxjVMKsni+OcWHIYz6bfxErMo/6N81U=,tag:5tHvuWaOvdvFRhJB8al4QQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
