apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: rayces-production
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:bvLV5COxe0fQZN6rzPhBNi5m2VFrhn1lU3nWtBHLLBfMumgDhP4dBwe5inectC9t14avhmRWQ4W2LEr+kFFMskk3k9jiXM1uDqMEQ0RXXYiStsff3egjI53nQzLE8PPychPHyJlqTC0UtVcD5GO8qBTAdrobWV+6ixZu4Ms+OFbxKp6D5JoUU7pp+Yvsgdlw/w2iph4b+Z5X5Ta/keaqIQpFRPKeo4uZ6jqJ00lYrsLQ9rmiKYRO7t5Jo7b5e1ANhxYPFjIKf0T0L8vKYPiGtZrVNOfUlk/Hvpz55KqV,iv:/WKdid7SQjY5HgmINFijF9jiyCnsSTZhLzkMoYrvYZs=,tag:Z1uzJkd4MQPKzG/sIAIliw==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUEk0cWVhYW10NUdqRlJu
            RHF0REdBN1cvMk5Uek9IUlEyOUtWVytzaVFvCjB1N21JZ2NMNTlDWnhhOGdNMVJp
            R2ZiVm44UXNVc0Zlb0xNN0Y4R0hJTlkKLS0tIEwrdjMxVXFTZXJ2a1ZGVkdMZjhj
            WXVCZkxnVVoydEtFZkZRYlNzRDYzZGMKFnwBYl4k7ovcvIHJSCvqyv/+AP/ChvYs
            4BnbLloN38jTICr/Q705DKLgSPstmCj5ENnCw7906t74IjkQlDtq+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T18:14:58Z"
    mac: ENC[AES256_GCM,data:yK4NTg1PMQVgiDyHh2/sku24oaztxRBCi3gyoaRQFZApIIRuh2zaFb6duqPKSPqB/QCPLOQN1PvjbYLwQPktE/+hTuxGQSpFDlOwAWMC1v+DXuCERD3bTHDJgxRLkCbjPq4irC4bXcilx5YD0V1eLmnzQbzB2/ZTN505QjZrFDY=,iv:FlCJ8lmuIQ1t7FAmy9JfKo3EHK87aGcclXRrKAh/l/s=,tag:ZUboLgH0s6fj+vqdpXFvKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
