apiVersion: v1
kind: Secret
metadata:
    name: ghcr-flux-system-credentials
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:va4FTg+JgjO6tLjYXqaUj/FhpfhrJnehH7vIcwBZztAxc0JBeTH/RpqWRshpvI6zhHBb72znUjbfgtK3eRAftyfTP7Cu9J/9dANWZRmWFyA3DCAe73p7RCWjCJK+m8tjnVyCoRc71bDwAYNmmm3+yc6ndSHk2HCyivsrAg8+NV4heefHpgdFjvF9h2wmj76VL7kgH/bE9K3cm59JVHHYd7L5mjXSmnqEO6DhknMqF6BOr0q7T/e8gO0vXjxQpC7j88CIILpP6NJoqyiVqSnWuKQl+AViFq+o2qlOY/zF,iv:ZstWBEo/2jspcDiGkHGB54f5G+nHARqUusmL92cKUCQ=,tag:v7PNrz3jaxfGVI5xejM+/A==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ1FCUFFtVkc3VFk1ZGVh
            dkk4U0pBeHNoUjQ2cmJrYTZJZ1BYUGtKbkcwCndPbHJGdjJENEQyRW44OGM0MFdq
            S1pKbzFrUFRiR3VwNEZxcGVpTDhFZk0KLS0tIHNNeTVnSEx6R2toOUMyQzFnWVlw
            cEZkeXpWbldMT3RWcGI0d1ExTHB4QkUKsBfjQAi9TjC3b59YUSwrcnmXrI6H+5tw
            BwtP82tksS3C72NZqbEpQwYD5RQHdZY/E4RBVg99glHTVf1xPd88NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:28:12Z"
    mac: ENC[AES256_GCM,data:Z6K0bOyYzocmKLduRLSGPgISWn459Bf1hChl47vOBi+t+2lhNmFwnkMPEhakJaq8TTi5TBpnun0qj4ug1AYzN+cucNDJTEmxwmPxLbIiTlWmE7UOBDrE14EbwPN0ZcK910XNn1atplFUz3CjtKEp6eEpz5boEFscUM5oMELUGRA=,iv:DKmhTeXkmxysC+JLZi1RoacrEhiNiMaEILvAsxy8COY=,tag:CRFPzJlEjddFcOozwqDIsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
