apiVersion: v1
kind: Secret
metadata:
    name: github-rayces-credentials
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:VcPijQk5W65G,iv:WTyWtJD3DHbjWsNCKiZLE36xbRW7/T9yh/SJlgVjUXA=,tag:Xtun6gvA22hlp9xuiPhzzw==,type:str]
    password: ENC[AES256_GCM,data:pxKw8wBZJ7wRCZLoa01ODsHhpKFt71I6iGcLtVmKI7bey/ywkBCHJQ==,iv:nLXgFFfBxRFTxlMMhDZqJ8kjnhquc4eazUbFsjHmdXI=,tag:E/utijGC0X6pmI1EWoTQhg==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBLy9lb0IvZ0V6ajZNTnRO
            NEtVWnFIUFd2Tno2SVU1WXpSVDBRbGFJRWhVCk8wWjZrM0M2SzUrY2JHT3NxUTFj
            eGJST3czSzFteVRZaXZPZE1CcWxTVXMKLS0tIEpBZG5Ja0xMRlFxVGltUE9kOGZH
            bkF4S0xpN2d2Yk5MaFZ5Qng1QTNTd0EKKxqDK5MPBOsbuz88xhjQzK6Q3W5CXj5M
            1G3wQcGquBbGd+SduKCsZlg5vfrXrNogeU8+p1bY476Ds63iu+Wb8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:33:13Z"
    mac: ENC[AES256_GCM,data:JszQDGJPM6TC/9FIqwtqBY4UiAcm4dJcN/J3KBHx2zbYH6sQY6q/ezPJ2y6N2iggviN6j4uvPFJwtpMQOrFZ7966FX2SlGYe/b/5X6azldmnOSLdprNP5wFOqIRC8a/t1TZZJLBICTZF4+4X88XKuQH+SM4vpVhWZcNhUXGL/LE=,iv:NcWzgy0DJNo07cINk8QErsuUfx/nOX3uad7CxAZ4Q54=,tag:A8GbQmO1G6jWlP5kLMycSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
