apiVersion: v1
kind: Secret
metadata:
    name: github-rayces-credentials
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2FUvltdgJX8O,iv:EIr+O33pXdoKVhoG4vISqy7+sYr+qSK3k5dmvhpYGt4=,tag:yLPldr1uFJlaBdb7C1UhLA==,type:str]
    password: ENC[AES256_GCM,data:mTSR4GyPyNqh8DDebEIg4HOSv16W5WOPt7W9EEnrAxyf6TU8Caq6Rw==,iv:HS8kFUqEWdTlJvioADoIrrKl11yZg7HADFNciIZiVq0=,tag:SGYlqq5x/mE70hUr+mvesQ==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR0FJbmI4ZVlkVUY4M0Mx
            d1BJRkZ2UHlyS20velpvQ2phdUVhV1c0a0JzCm9ZNWlLSFFvNVpBK2diTTVlNzZn
            NURLTEUzOHh0b2xVL2dQS1hNOWp6LzgKLS0tIFJXQXpRaFhYd2ZvTVJrSVRBU0ZO
            ZmF2cVY3akpUbFZJOFdUWEdRcmFWMFEKhQvP8YRTUY97y4+lQu+yl23vbo72X2x2
            LepAeJNk4qUhApz5NUNqv8A+Jce9H99BczaxIbcJlAV7BDSw76SYpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T18:06:19Z"
    mac: ENC[AES256_GCM,data:fyB2opxT5hsrbhEG6q3hxSmg5gAyKFrRTYePuT+UkhepNMKLcuW93r4MFloLVSrT/xPdwU3JYC5I6eOcrrJ/+PQWLbEJkpsi81APIrHgDYaj4E3vxSSzW+EvUKI3BWZs3s26IV/Cy5pJAwlzmJaCQwpn7T7n0MXJCzTn7TpcGDI=,iv:H6tj9cVB5FSeOXDwjuk9ESd0EpIAEl+xcwANKth7RBg=,tag:fHBwY6Sjpw6GAztmjpo7pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
