apiVersion: v1
kind: Secret
metadata:
    name: flux-write-credentials
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:zevW3e/GzYKVQRI/pym8+nZJUcS65jHqpxNEwsD6iHusFfLL1hEq/giJtGpvfSgZj+wsYWbolxf2grCBJ0LPTcabJysooFHFCI2Vcyv7vFtBvP7snxeLzpGEMnqJd1n0Tu+tTDEcTBUebwxujltKs4IJ9IjNnnLtV8jbzJcE1krHVmJ13Vr589Lwqh02VMIhFAE7GzWHPPbpAhwdf25BlPwcXrnSezaEr8vY/Lpt8wa0GKMZ3MqxW+8D0w8oYJtXt/agUV3+Yem4zSSs3A0IKN5yinb9Emr6vTiRtngNHhiy1XTWiulSd/KamSuUA/2eyN0IFIPH/kUrVKRKT9GZruof1VUUZBVlhr9yKnD9MvK1YYXjlOMQbO99995tuiD+KSA0Bqxts5S8vOQCV8lOwv2QESPHvjDJbqlM6lji0gjG1OZf2Xe2yN7x/C7Zvke1T/9q+pmL4ri2xtxXnanEkBQGvvoy7L2xC8hWsVWPKoeS7aOJl6i5Yr7U9jegMWK/eGSe59Ak9htCP4ux4GwF7iMEOsHuHcMDC8yA,iv:sZQdUDXv39MmziQlQFJuhmj5IGPSY4pK7+/kOSbpcJ4=,tag:0Qoe0uIM9UxLQzAEES2Lrg==,type:str]
    identity.pub: ENC[AES256_GCM,data:cFw03+oIO1acbX2NkstlHCJnh/a79cj6e/t4pYL7ntAVlRPXLX6/go3h0Dl1Sz249DfJuwFs8QKfaRs8hQ3/oR4n2J57JTS4Zr+JPsIwOuvEfefhA849nIyHWzoYJcTjhns6QQMG,iv:Vz5AmrhHtUVDjhJNKMYb2AOqFHf6ClCBNZjLix5tHHg=,tag:xfakPFKnTtt3o3G34mRp0Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:K6BK8h9WQMC3UQq9ADZ/RjcyQv17tggW9Q/qkUp8DxrZkAuBTwp7MwFq6pWo5YZHMWzK1Y0624T5roGwCXUhDp9dkKgAnzHsvOvECA1UETNICw3oicLUS/NYDg==,iv:NuIK1Ng/CNMfw8vPUKfN4fJd4qmh5HF8fvUfPgvazS4=,tag:IFZBo7uC+s8dQ7EIQAr/uQ==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZGlvcEt4dkdndWZqa2lP
            bTQrY3BKbmUrYmlQckFKUU41b0hwU08rNFZVCmFPZ3lLWk5vdm9YVlV5OURIREZY
            bHoyb1Z5dFpmY09qRzlNc0tYTVllLzgKLS0tIDFTM3VGa3k3RmowN0ovSEk5WS9C
            cXUyVzUxdVlaQWlSLyt6cWVEaElXMjAK/QGl2q8mk1/+z13+JmC8Dvb02Jxn3Fhu
            1UQos4g8fN2QDcvA4+CHUrHbAM6GsnfPqY35T85CMof7eDzfeh6/fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:24:07Z"
    mac: ENC[AES256_GCM,data:uysllkYXTG4ZRlDWKgNxpB2qkGdGY2Ec6Osk8u885fHo22wGwCU0+Kf23pzoVWuwtc3q4d6y9Y3WLMkNAfSe8HUBnlwd8LSo/cYnRBNj7i+hflBkWOHpsQeKPzpTntJL+qkN2c2r5qn44k3KUcn5Odjm+R1cnqUv8t/FopQYyXM=,iv:LNZhwOS+2imPIYe+3OuehNFrGsD74kf1WJGSMoDUKu0=,tag:OeYj6XH3QaKUVB8J34A3KA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
