apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: rayces-production
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:M+lyem5SlQUwlnpVxnK8ocAx4MWHYcZKz2rT7PKyGREMdA0G/V2Ka3KH9riezdUN96+wsy0k5ueluZFY36VjKtFoUXuYACKVCqrjAUFa7jfkUIco1+yJUXTNu3tWzxoWO5fBE9XE4Ttg7R/ka60NViP36G2c9z7QC6YmiuHJCsL7cS/CKSCN5H7YO0nK/dromtbbRMI1XV4llirK1W78U5JI9X3eRkYzmVGSRGBb1x0=,iv:Py8fG4SKJ9BfDPgHNFU2jYrdWoSX6uYm/S2RJZzGDns=,tag:xSw8gOEJnGDJNp0T6w6m4g==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMVUrY1h2RCswYmtFSCta
            YmkyRWs4a21iSGZoYS9Wd1hVckNCZy8ydVNJCjM3VWNZd1RqaHlKRzhOQXdsNmZ3
            L1UrTTBBWENMRWVzd2t3RTVNcmwrYVUKLS0tIFpTalkzdFhDZTdUU2tPRTNKWGFl
            WEVuMk4wSEJzMHhZTXBCUGpUa0p0ODgKO3CPlhkzq/mUP4enr5erYNUzVflmQyGy
            VuMzlfiSUsTgYuSYtI7tUzhv5LiDITKMi1sFJqIwwWq4hQYoG2lIDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:31:30Z"
    mac: ENC[AES256_GCM,data:GDKMMDICSUjVE/rh5CXHTOTcGZMPIHagJTjmRn1mYebyZlF9f+ppVD6pCXlq9EFuzVPp9V01y0OPE+L91O6qQBe4KFjhyJBNSFnHCbEgWfdSx5eZI2Vq95h9m4iwsQL9hUUF8mIDpT3neb06tXDP0NnBT34XIBoyVy+VRFT4lu4=,iv:ODUZfKUWWndcqfbXE6DWHr40KjVwb6zbcSD2aqzsFWg=,tag:r9GlFT0SH/QjbRL/qvyxtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
