apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rayces-v3
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/canriquez/rayces-v3
  ref:
    branch: main
  secretRef:
    name: github-rayces-credentials
