apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rayces
  namespace: rayces-production
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/rayces
      sourceRef:
        kind: GitRepository
        name: rayces-v3
        namespace: flux-system
      interval: 1m
  values:
    global:
      namespace: rayces-production
      secretName: raycesv3-environment
    images:
      backend:
        repository: ghcr.io/canriquez/rayces-backend
        tag: "20260322-d8f698e" # {"$imagepolicy": "flux-system:rayces-backend:tag"}
        pullPolicy: Always
        pullSecret: ghcr-credentials
      frontend:
        repository: ghcr.io/canriquez/rayces-frontend
        tag: "20260322-d8f698e" # {"$imagepolicy": "flux-system:rayces-frontend:tag"}
        pullPolicy: Always
        pullSecret: ghcr-credentials
    rails:
      replicas: 2
      env: production
      autoSeed: false
    sidekiq:
      concurrency: "10"
    nextjs:
      replicas: 2
      command: ["node", "server.js"]
      nodeEnv: production
    mailcatcher:
      enabled: false
    cloudflare:
      enabled: true
      replicas: 2
      tunnel: rayces-production
      ingress:
        appHostname: citas.rayces.com
    postgres:
      metrics:
        enabled: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
