apiVersion: v1
data:
    SMTP_PASSWORD: ENC[AES256_GCM,data:ZnkV/XyKQjh8h7hJv+g64A2tJV+URBKEP2l0eF7YTC1qNnnAAQXwMxV7QJU0yK+t+eMG15JF/89e2HogP7cQeD6LsPj+SEQfsYl/9/vWyLKAK2TnzFte/DYBmWELFm2RtH1N8S1pGhTlg6RdXhbjh+NjAYuoKbQR,iv:j1ALZ2RAw2ekPj5CA0FsrzgfKGPis44YgHE4xqC7aSM=,tag:EwMgVaJBCgTOX4mk8NQQqA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-smtp-credentials
    namespace: monitoring
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVTJyQmI2Q2NwbzZoZTdN
            c29kbWlHdGxGMkJQU1VaMkExaXpxMkt5ejNNCm5zMkhGL0VSRGRxOTE0Mjk4cWxX
            dVhUSHRTeGh1V3VzMkYwcGRyR1I4eU0KLS0tIDBtU3VkMm1IZWRXeTBrWmx3UDV3
            QnlLT2JRVWJPb0dtK1orYWdrdDAxWmcKx+3XyTdSGYyCZgut5KlROGnwYxugjLsP
            HGncOigWTjssKVIrRtZG8lp9mmSsmqc5BboiIRzcP/2dbXpZzvy/0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:10:11Z"
    mac: ENC[AES256_GCM,data:M/dDEjazXWhm4QvAdHLWx2xid03jScgTtvyIRPxcxFP9FNgG6AlWx63gvqlpLzTuBl3Cxa7qsn0ISaOj3rSx4MdLU78pjtKlSgvc0PyZDwLTBndgctbcJPcn3QKNc89GHNoBjoX0VpVVeFA3bZCvsOZSb0UzW8X0ScPhqZoeXOE=,iv:MKe4vHybLrH9KWA1Hczvzby6iqVSkDctd9gbwsfbowo=,tag:yS/auaRlVj8y4A6W54v+VA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
