apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
data:
    admin-user: ENC[AES256_GCM,data:5f4ONNGSZAXseUjL,iv:rW30B4bBa6jms/s79xDI3g9MUtqhA2LLQC8+gsjIFpk=,tag:msk/j1BCzHp38Yg49e8lsQ==,type:str]
    admin-password: ENC[AES256_GCM,data:LOCVYzMayQn/z/Yg0+fsHB8TNc4OiehUGl+LJmBJJFs=,iv:UoMFTq/EXKK7PtfFcPrwhNnfQAjzScFByGpHZa4ZkDk=,tag:80nemZbO1uLWSx7NdNgJxg==,type:str]
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SlZBRnltaW5vODRENDZK
            QTgraDhVUldtd3hsN1VLS0d3WldKVHQ5d2g4CjZMTk1tbTRBbzN1V1NpMlpYVEha
            REFWQUNEd0Mwa1BxbVN5WEdFWlphcjQKLS0tIEhLeVY0anRkNzRkR1FndGkyRDBy
            ZjR3Tzc2Nmg5c2cvUEViY2o3YjBwTkUK9tp+H1JloRMixzyv5UPFCLaUfGA1tI29
            HOzprjfSxCenHGJsc63Vj3sgRO1JRfcUquElu/P0ai8YJrX8TzzyqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T23:09:52Z"
    mac: ENC[AES256_GCM,data:7mCW2ZOE3uE5RoBSkXgygsUNXAH+1dhL5sa5E3OJvG4QsXucL8IuR6pDKk1NciqTT/ru7xwo17hjigKgnu1wUWSwa5SR2/PxEDXr57zKrvmGI5HocRk+k+/iQxXPIoKQz5xVMgj0eZWE/gSwwMvo1E9Fv4rEIIttGbwnnUMvwHQ=,iv:YYjug/jX5rPyDE5h47WKGgOi+oHa1Dk0JEyaZJq2oEo=,tag:V765GCY7v7nZdNd7hyK8yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
