apiVersion: v1
data:
    SMTP_PASSWORD: ENC[AES256_GCM,data:anPgQVWs2ldrXawNS9f7RwCxAko9pwNdsiriRO5HlyEkbHKtgyQbnV/2EcEeMXaON3Iijd/k0wqKYtDZUQA5XLdOAj7Kbh0fHF4+AxAgslzOKak1RFaecIBVnwce9kd3iTG8sYdfzomqsbo4Zb1+CrVIZF4YRX8U,iv:4xHS+4dbFjfH0Y1579f8kc9ya0E2Imx0QopemmdkR/Y=,tag:YwDUYnxPaojFhsnONda4Lg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:F99jIjrE8935NvP7Rjr4u+rV3O9Ff1aArEIKNvKzPbE=,iv:RhXyC9mX9rgvAW4Tg66ZBt9IdME07hMuJH/ByjcXlkw=,tag:/xhZ+50sRM8DtsCKURs0gg==,type:str]
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:MP5rDK39NSm7jqf+,iv:d0N11fEd7FsssFKUtm+u2cED7KgdTCdz5uNxPsVXENc=,tag:6b68oVvdqJQffvRG+GdY+g==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:9OWrBogX5ImZEkOiDVFyousWllBKY6Dr19OFzXnMmufexnAdPPrqbWxADTo=,iv:0JQjKiEOvKzknlWKcSTTt/gekNr702augZrPB8HuNqo=,tag:uE+ie1B4HfKZVOKBITjH/Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-smtp-credentials
    namespace: monitoring
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdzl4L1JjNjZ2T2pMOHV1
            REw3VE8vdTFWTEFxaXpPSXlGQlY2YWorWVIwClROdzA5Mm9OZ2syWGo2WXg2M2FH
            Z1ZxaE9lOVVLZ1FqRnZQMkNldXpSTVEKLS0tIEoyZU5Cc1JGcDZEcEFUMmcydHdF
            TG5aTGY3WmxTTm9UTWhyS3VZd01CRk0KVI7kZaTL3xbILzbsS4ZGD8P5rdV0khi0
            gxGc8u9GZ/ZtUI9lAQ5G2Nvy4HZ6CppktI0qYe55Tl4RGa70131gjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T22:22:59Z"
    mac: ENC[AES256_GCM,data:Pd+FwxRsDC+5qXCdj21kC2mGkJbUrRKtAmxkdChwjv2f8NoLl/JjT302PoZY8oiv/KWZmB9ljH2CR5VMfW9R+dOw9tNhv6wSoDMV+at6mb6i7ZUGCac4JQLcLUR+zOEIqRAEGR2S8xCw0jwgI2Of5SHBo7KsZKlwCldXIe+pJdY=,iv:gyUqMhlnx6880z2Z0zoWE3Avuw5Hh3sRqA0xvdJi9ew=,tag:6LVf2qKPuzNewjAZ6vbvcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
