apiVersion: v1
data:
    SMTP_PASSWORD: ENC[AES256_GCM,data:xi2AA7Q9EtN6LKgqbq46j0lvB0OchaIH3iUxRJ8PxByw1TV78SzXrybFd5KomG5FamEXF/9FQx9yGo28xaBLbW+ykiQzy+kxaok7/H4S9Aug6yQlav0H2tFbr44QWZXzFWitZZZUISFy5Hrj9D1M2uDi+E+AZVnW,iv:A/4rxeXx8v6tDypKbmllhlNZHEpPZOXV6IaarQ66l1o=,tag:lAdlefh+8xE+C8wit5xkBA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:UV6Eb5ZilmlDzHMYG1PyGomjy5pi7ojQMPkKi3C7ItM=,iv:HgmjncnawhGg6mhrGcYWSiZuGT3yXim5NIw3uQBks9w=,tag:IgQRiLXp+eSmOFqovm72KA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-smtp-credentials
    namespace: monitoring
sops:
    age:
        - recipient: age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNFVJN3QvV1V6OS9ZL05N
            YkpVc0Q2Z3RhbFRXczBTQ0c1NmRkNkVYTXdnClA1eVVSaGpWMlcvZEpnWE96SHVO
            T3d0ZTR5YndVV2pGSU5yamNSblU0QW8KLS0tIGxYaTArajlDTmhOM2plQWpMbUs5
            ZTdGNllKaEEzbTNhTnh3STdpRUVXSTgKpfCRCvc8nBuW/u+5FEFT6Bcvqnn188rw
            IvwTsOYGroRS8HwPrIGA0G0eopRjd53BytDoXOMO9/2f73SHt9F7sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T23:08:59Z"
    mac: ENC[AES256_GCM,data:WmCmAdn/Zq0co1ziXk/yOTnZvr/2LOhUEidHnUz8TYffbgQzUHWkWf9SKbDcbvcDLe5EiLvPxKemhdDTHSR2UaWR4LMJQCpYcslpGSaJNuWYfquF9uTeU+Dw+cV/1qmmP1dQSPyQsjBvZeQt9FKeTMfvS7YR0mRALJSSUkwvIp0=,iv:wD7yELkV3TT5QrPDYSFhYscbv/y+iLyd+0FTkA/PZiE=,tag:gNpIjqBsIDejl8yFnk9F7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
